### PR TITLE
Follow HTTP redirects (max. 5 redirects).

### PR DESCRIPTION
**Pull request by jiwandono**
Request method doesn't follow HTTP redirects, resulting in empty strings. So I set the CURLOPT_FOLLOWLOCATION flag to 1, and set the CURLOPT_MAXREDIRS to 5.

### CODE REVIEW

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
@jiwandono I add you to the collaborators, and can you tell me your npm username? I will add you to the authors list.
This module is up to you.

**Comment by jiwandono** [comment]
Thank you. Actually I'm new to nodejs, and while this module fulfills my need, apparently I'm doing it wrong: synchronous/blocking codes in nodejs is not a good idea. I just switched to `request` package and very unlikely I will use `httpsync` anymore.

**Comment by fengmk2** [comment]
@jiwandono yeah, we should never use `httpsync` in common case on node.js. Because all io in node.js is async.

**Pull request merged**
